# Generated by Django 5.0.4 on 2024-05-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='descrição dos serviços do estabelcimento'),
        ),
        migrations.AddField(
            model_name='post',
            name='lighting_control_environment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='preferential_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='soundproof_environment',
            field=models.BooleanField(default=False),
        ),
    ]
